# Generated by Django 4.2 on 2023-04-21 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_cpf_alter_employee_name_and_more'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='project.supervisor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
