# Generated by Django 4.2 on 2023-04-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_deparment_name'),
        ('employee', '0002_alter_employee_cpf_alter_employee_name_and_more'),
        ('project', '0002_remove_supervisor_project_id_project_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='estimated_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('name', 'department_id')},
        ),
        migrations.CreateModel(
            name='EmployeeWorkProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.FloatField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
            options={
                'unique_together': {('project', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='work_group',
            field=models.ManyToManyField(through='project.EmployeeWorkProject', to='employee.employee'),
        ),
    ]
