# Generated by Django 4.2 on 2023-04-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_cpf_alter_employee_name_and_more'),
        ('project', '0003_alter_project_estimated_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeworkproject',
            unique_together={('employee',)},
        ),
        migrations.AddField(
            model_name='project',
            name='work_group',
            field=models.ManyToManyField(to='project.employeeworkproject'),
        ),
        migrations.RemoveField(
            model_name='employeeworkproject',
            name='project',
        ),
    ]
